name: TEssentials
main: me.taikun8.essentials.Main
version: 0.3 Alpha
author: Taikun8
description: Essentials napisany przez Taikun8.

commands:
  broadcast:
    description: Globalna wiadomosc.
  changelore:
    description: Zmienia opis przedmiotu.
  changename:
    description: Zmienia nazwe przedmiotu.
  chat:
    description: Manipulacja chatem.
  ci:
    description: Czyszczenie ekwipunku.
  enchant:
    description: Zmienia opis przedmiotu.
  fly:
    description: Zmienia nazwe przedmiotu.
  gamemode:
    description: Manipulacja chatem.
    aliases: [gm, gamem, gmode]
  head:
    description: Dostaje sie glowe danego gracza.
  heal:
    description: Zmienia opis przedmiotu.
  setspawn:
    description: Zmienia nazwe przedmiotu.
  spawn:
    description: Manipulacja chatem.
  tp:
    description: Teleportacja pomiedzy graczami.
  treload:
    description: Zmienia opis przedmiotu.
  helpop:
    description: Komunikacja z administratorem.
    aliases: [pomoc, admin]
  help:
    description: Lista komend dostepnych.
  msg:
    description: Prywatna wiadomosc.
    aliases: [tell, pw]
  back:
    description: Powrot do poprzedniej lokalizacji.
  whois:
    description: Informacje na temat gracza.
  invsee:
    description: Ekwipunek gracza.
  world:
    description: Teleportacja pomiedzy swiatami.
  time:
    description: Zmiana czasu na serwerze.
  weather:
    description: Zmiana pogody na serwerze.
  tppos:
    description: Teleportacja pomiedzy koordynatami na serwerze.
  reply:
    description: Odpowiada na prywatna wiadomosc.
    aliases: [r, re]
  motd:
    description: Zmienia globalne MOTD.
permissions:
  tessentials.*:
    default: false
    children:
       tessentials.broadcast: true
       tessentials.changelore: true
       tessentials.changename: true
       tessentials.chat: true
       tessentials.chat.bypass: true
       tessentials.clearinv: true
       tessentials.enchant: true
       tessentials.fly: true
       tessentials.gamemode: true
       tessentials.head: true
       tessentials.heal: true
       tessentials.setspawn: true
       tessentials.spawn: true
       tessentials.tp: true
       tessentials.treload: true
       tessentials.helpop: true
       tessentials.help: true
       tessentials.msg: true
       tessentials.back: true
       tessentials.whois: true
       tessentials.invsee: true
       tessentials.reply: true
       tessentials.world: true
       tessentials.motd: true
       tessentials.time: true
       tessentials.weather: true
       tessentials.tppos: true
       tessentials.clearmsg: true
       tessentials.sign: true
       tessentials.helpop.see: true